version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install

  echo_version:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: echo npm version
          command: npm -v

  lint_one:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: check test1.js lint
          command: npm run lint1

  lint_two:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: check test2.js lint
          command: npm run lint2

workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - echo_version
      - lint_one:
        requires:
          - build