version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: check
          command: ls -la
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  echo_version:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: echo npm version
          command: npm -v
  lint_one:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: check
          command: |
            ls -la
      - run:
          name: check test1.js lint
          command: npm run lint1

workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - echo_version
      - lint_one:
          requires:
            - build