version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: node_modules
          paths:
            - node_modules

  echo_version:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: echo npm version
          command: npm -v

  lint1:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: check test1.js lint
          command: npm run lint1

  lint2:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: check test2.js lint
          command: npm run lint2


workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - echo_version
      - lint1:
          requires:
            - build
      - lint2:
          requires:
            - build